import type React from "react";
import { createContext, useContext, useState } from "react";

export type Language = "en" | "te" | "hi";

const translations = {
  en: {
    appName: "FarmConnect",
    tagline: "Direct from Farm to You",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    email: "Email",
    phone: "Phone Number",
    name: "Full Name",
    location: "Location",
    password: "Password",
    role: "I am a",
    farmer: "Farmer",
    buyer: "Buyer",
    sellCrop: "🌾 Sell Crop",
    addListing: "Add Listing",
    myListings: "My Listings",
    orders: "Orders",
    profile: "Profile",
    browse: "Browse",
    search: "Search",
    home: "Home",
    cropName: "Crop Name",
    quantity: "Quantity",
    pricePerUnit: "Price per Unit (₹)",
    unit: "Unit",
    description: "Description",
    detectLocation: "📍 Detect Location",
    voiceInput: "🎤 Voice Input",
    suggestedPrice: "💡 Suggested Price",
    marketPrice: "Market Price",
    yourPrice: "Your Price",
    demandLevel: "Demand",
    high: "High",
    medium: "Medium",
    low: "Low",
    accept: "✅ Accept",
    reject: "❌ Reject",
    placeOrder: "🛒 Place Order",
    contactFarmer: "Contact Farmer",
    callFarmer: "📞 Call",
    whatsapp: "💬 WhatsApp",
    share: "📤 Share",
    viewProfile: "View Profile",
    estDelivery: "Est. delivery",
    km: "km away",
    verifiedBadge: "✅ Verified Farmer",
    needHelp: "❓ Need Help",
    supportTitle: "Helpline",
    fraudWarning: "⚠️ Price Alert",
    delete: "Delete",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    rating: "Rating",
    writeReview: "Write a Review",
    submitReview: "Submit Review",
    receipt: "🧾 View Receipt",
    printReceipt: "🖨️ Print Receipt",
    notifications: "Notifications",
    noListings: "No listings yet. Tap Sell Crop to add one!",
    noOrders: "No orders yet.",
    villageAgent: "🏘️ Village Agent Program",
    agentDesc:
      "Our village agents help farmers with digital access, order pickup, and payments. Contact your nearest agent at 1800-XXX-XXXX.",
    tutorials: "📹 Video Tutorials",
    priceHistory: "Price History (7 days)",
    welcomeFarmer: "Welcome back,",
    welcomeBuyer: "Find Fresh Produce",
    filterCrop: "Crop Type",
    filterPrice: "Price Range",
    filterLocation: "Location",
    applyFilters: "Apply",
    clearFilters: "Clear",
    allCrops: "All Crops",
    orderQty: "Order Quantity",
    confirmOrder: "Confirm Order",
    orderPlaced: "Order placed successfully!",
    reviewsTitle: "Farmer Reviews",
    avgRating: "Average Rating",
    enterLocation: "Enter location...",
    searchPlaceholder: "Search crops, farmers...",
    noResults: "No results found",
    priceTrend: "📈 Price Trend",
  },
  te: {
    appName: "ఫార్మ్‌కనెక్ట్",
    tagline: "పొలం నుండి నేరుగా మీకు",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    logout: "లాగ్ అవుట్",
    email: "ఇమెయిల్",
    phone: "ఫోన్ నంబర్",
    name: "పూర్తి పేరు",
    location: "స్థానం",
    password: "పాస్వర్డ్",
    role: "నేను ఒక",
    farmer: "రైతు",
    buyer: "కొనుగోలుదారు",
    sellCrop: "🌾 పంట అమ్మండి",
    addListing: "జాబితా జోడించు",
    myListings: "నా జాబితాలు",
    orders: "ఆర్డర్లు",
    profile: "ప్రొఫైల్",
    browse: "బ్రౌజ్",
    search: "శోధించు",
    home: "హోమ్",
    cropName: "పంట పేరు",
    quantity: "పరిమాణం",
    pricePerUnit: "ధర (₹)",
    unit: "యూనిట్",
    description: "వివరణ",
    detectLocation: "📍 స్థానం గుర్తించు",
    voiceInput: "🎤 వాయిస్ ఇన్పుట్",
    suggestedPrice: "💡 సూచించిన ధర",
    marketPrice: "మార్కెట్ ధర",
    yourPrice: "మీ ధర",
    demandLevel: "డిమాండ్",
    high: "అధికం",
    medium: "మధ్యమం",
    low: "తక్కువ",
    accept: "✅ అంగీకరించు",
    reject: "❌ తిరస్కరించు",
    placeOrder: "🛒 ఆర్డర్ చేయి",
    contactFarmer: "రైతుని సంప్రదించు",
    callFarmer: "📞 కాల్",
    whatsapp: "💬 వాట్సాప్",
    share: "📤 షేర్",
    viewProfile: "ప్రొఫైల్ చూడు",
    estDelivery: "డెలివరీ",
    km: "కి.మీ దూరం",
    verifiedBadge: "✅ ధృవీకరించిన రైతు",
    needHelp: "❓ సహాయం కావాలా",
    supportTitle: "హెల్ప్‌లైన్",
    fraudWarning: "⚠️ ధర హెచ్చరిక",
    delete: "తొలగించు",
    edit: "మార్చు",
    save: "సేవ్",
    cancel: "రద్దు",
    rating: "రేటింగ్",
    writeReview: "రివ్యూ రాయండి",
    submitReview: "రివ్యూ సమర్పించు",
    receipt: "🧾 రసీదు చూడు",
    printReceipt: "🖨️ రసీదు ప్రింట్",
    notifications: "నోటిఫికేషన్లు",
    noListings: "జాబితాలు లేవు. పంట అమ్మండి బటన్ నొక్కండి!",
    noOrders: "ఆర్డర్లు లేవు.",
    villageAgent: "🏘️ గ్రామ ఏజెంట్ కార్యక్రమం",
    agentDesc:
      "మా గ్రామ ఏజెంట్లు రైతులకు డిజిటల్ యాక్సెస్, ఆర్డర్ పికప్ మరియు చెల్లింపులలో సహాయం చేస్తారు.",
    tutorials: "📹 వీడియో ట్యుటోరియల్స్",
    priceHistory: "ధర చరిత్ర (7 రోజులు)",
    welcomeFarmer: "స్వాగతం,",
    welcomeBuyer: "తాజా పంటలు కనుగొనండి",
    filterCrop: "పంట రకం",
    filterPrice: "ధర పరిధి",
    filterLocation: "స్థానం",
    applyFilters: "వర్తించు",
    clearFilters: "క్లియర్",
    allCrops: "అన్ని పంటలు",
    orderQty: "ఆర్డర్ పరిమాణం",
    confirmOrder: "ఆర్డర్ నిర్ధారించు",
    orderPlaced: "ఆర్డర్ విజయవంతంగా చేయబడింది!",
    reviewsTitle: "రైతు సమీక్షలు",
    avgRating: "సగటు రేటింగ్",
    enterLocation: "స్థానం నమోదు చేయండి...",
    searchPlaceholder: "పంటలు, రైతులు శోధించండి...",
    noResults: "ఫలితాలు కనుగొనబడలేదు",
    priceTrend: "📈 ధర ట్రెండ్",
  },
  hi: {
    appName: "फार्मकनेक्ट",
    tagline: "खेत से सीधे आपके पास",
    login: "लॉगिन",
    signup: "साइन अप",
    logout: "लॉग आउट",
    email: "ईमेल",
    phone: "फोन नंबर",
    name: "पूरा नाम",
    location: "स्थान",
    password: "पासवर्ड",
    role: "मैं हूँ",
    farmer: "किसान",
    buyer: "खरीदार",
    sellCrop: "🌾 फसल बेचें",
    addListing: "लिस्टिंग जोड़ें",
    myListings: "मेरी लिस्टिंग",
    orders: "ऑर्डर",
    profile: "प्रोफाइल",
    browse: "ब्राउज़",
    search: "खोजें",
    home: "होम",
    cropName: "फसल का नाम",
    quantity: "मात्रा",
    pricePerUnit: "मूल्य (₹)",
    unit: "यूनिट",
    description: "विवरण",
    detectLocation: "📍 स्थान पता करें",
    voiceInput: "🎤 आवाज़ इनपुट",
    suggestedPrice: "💡 सुझाया मूल्य",
    marketPrice: "बाज़ार मूल्य",
    yourPrice: "आपका मूल्य",
    demandLevel: "माँग",
    high: "अधिक",
    medium: "मध्यम",
    low: "कम",
    accept: "✅ स्वीकार",
    reject: "❌ अस्वीकार",
    placeOrder: "🛒 ऑर्डर दें",
    contactFarmer: "किसान से संपर्क",
    callFarmer: "📞 कॉल",
    whatsapp: "💬 व्हाट्सएप",
    share: "📤 शेयर",
    viewProfile: "प्रोफाइल देखें",
    estDelivery: "अनुमानित डिलीवरी",
    km: "किमी दूर",
    verifiedBadge: "✅ सत्यापित किसान",
    needHelp: "❓ सहायता चाहिए",
    supportTitle: "हेल्पलाइन",
    fraudWarning: "⚠️ मूल्य चेतावनी",
    delete: "हटाएं",
    edit: "संपादित करें",
    save: "सहेजें",
    cancel: "रद्द करें",
    rating: "रेटिंग",
    writeReview: "समीक्षा लिखें",
    submitReview: "समीक्षा सबमिट करें",
    receipt: "🧾 रसीद देखें",
    printReceipt: "🖨️ रसीद प्रिंट करें",
    notifications: "सूचनाएं",
    noListings: "कोई लिस्टिंग नहीं। फसल बेचें बटन दबाएं!",
    noOrders: "कोई ऑर्डर नहीं।",
    villageAgent: "🏘️ ग्राम एजेंट कार्यक्रम",
    agentDesc:
      "हमारे ग्राम एजेंट किसानों को डिजिटल एक्सेस, ऑर्डर पिकअप और भुगतान में मदद करते हैं।",
    tutorials: "📹 वीडियो ट्यूटोरियल",
    priceHistory: "मूल्य इतिहास (7 दिन)",
    welcomeFarmer: "स्वागत है,",
    welcomeBuyer: "ताजी फसल खोजें",
    filterCrop: "फसल प्रकार",
    filterPrice: "मूल्य सीमा",
    filterLocation: "स्थान",
    applyFilters: "लागू करें",
    clearFilters: "साफ करें",
    allCrops: "सभी फसलें",
    orderQty: "ऑर्डर मात्रा",
    confirmOrder: "ऑर्डर की पुष्टि करें",
    orderPlaced: "ऑर्डर सफलतापूर्वक दिया गया!",
    reviewsTitle: "किसान समीक्षाएं",
    avgRating: "औसत रेटिंग",
    enterLocation: "स्थान दर्ज करें...",
    searchPlaceholder: "फसलें, किसान खोजें...",
    noResults: "कोई परिणाम नहीं मिला",
    priceTrend: "📈 मूल्य प्रवृत्ति",
  },
};

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [lang, setLang] = useState<Language>("en");
  const t = (key: TranslationKey): string =>
    translations[lang][key] ?? translations.en[key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);
